// generated by https://www.mockaroo.com/

export const teams = [
  {
    id: 0,
    name: 'all-team',
    parentTeamId: null,
  },
  {
    id: 1,
    name: 'team-1',
    parentTeamId: 0,
  },
  {
    id: 2,
    name: 'team-2',
    parentTeamId: 1,
  },
  {
    id: 3,
    name: 'team-3',
    parentTeamId: 1,
  },
  {
    id: 4,
    name: 'team-4',
    parentTeamId: 0,
  },
  {
    id: 5,
    name: 'team-5',
    parentTeamId: 4,
  },
];
